[workspace]
resolver = "2"
members = [
    "crates/app",
    "crates/cli",
    "crates/platform-store",
    "crates/capture",
    "crates/transform",
    "crates/delivery",
    "crates/types",
    "ci/handbook",
]
default-members = ["crates/app"]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/Migraloop/Migraloop"

[workspace.dependencies]
migraloop-cli = { path = "crates/cli" }
migraloop-platform-store = { path = "crates/platform-store" }
migraloop-capture = { path = "crates/capture" }
migraloop-transform = { path = "crates/transform" }
migraloop-delivery = { path = "crates/delivery" }
migraloop-types = { path = "crates/types" }
clap = { version = "4.5", features = ["derive", "env"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.9"
sqlx = { version = "0.8", features = ["runtime-tokio", "tls-rustls", "postgres", "migrate"] }
tokio = { version = "1.43", features = ["macros", "rt-multi-thread", "process", "signal"] }
thiserror = "2.0"
mongodb = { version = "3.8", default-features = true }
bson = "2.15"

chrono = { version = "0.4", default-features = false, features = ["clock", "std", "serde"] }
chrono-tz = "0.10"
oracle = "0.6"
