[package]
name = "migraloop-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Operator CLI for the DB Sync Platform"

[dependencies]
chrono-tz = { workspace = true }
clap = { workspace = true }
migraloop-capture = { workspace = true }
migraloop-delivery = { workspace = true }
migraloop-platform-store = { workspace = true }
migraloop-transform = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
tokio = { workspace = true }
thiserror = { workspace = true }
