-- Lab DB-level load escape hatch (issue #87).
-- Load into disposable Lab Oracle via compose exec sqlplus — not a Lab Scenario.
-- Pair with lab/escape-hatch/deployment.yaml for ordinary migraloop apply/sync/inspect.
WHENEVER SQLERROR EXIT SQL.SQLCODE
SET FEEDBACK ON

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE LAB_ESCAPE_CUSTOMERS PURGE';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

CREATE TABLE LAB_ESCAPE_CUSTOMERS (
  ID NUMBER PRIMARY KEY,
  NAME VARCHAR2(100) NOT NULL,
  EMAIL VARCHAR2(200)
);

ALTER TABLE LAB_ESCAPE_CUSTOMERS ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;

INSERT INTO LAB_ESCAPE_CUSTOMERS (ID, NAME, EMAIL) VALUES (1, 'Alice', 'alice@example.com');
INSERT INTO LAB_ESCAPE_CUSTOMERS (ID, NAME, EMAIL) VALUES (2, 'Bob', 'bob@example.com');
COMMIT;

SELECT COUNT(*) AS LOADED_ROWS FROM LAB_ESCAPE_CUSTOMERS;
EXIT;
