[package]
name = "migraloop-transform"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Rich Transform and Affect Analysis"

[dependencies]
migraloop-types = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
